"""add language to posts

Revision ID: 21428d058aec
Revises: 41fd3ae556d0
Create Date: 2018-08-07 16:45:57.330968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21428d058aec'
down_revision = '41fd3ae556d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
