"""followers

Revision ID: 602dc76ca17e
Revises: 6bb44c0c6f61
Create Date: 2018-08-03 10:34:38.548508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '602dc76ca17e'
down_revision = '6bb44c0c6f61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follwers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follwers')
    # ### end Alembic commands ###
